library(lubridate)
library(evd)
setwd("~/FACDapp/Newtons_code")
source("ComputeIS.R")
source("ComputeGrad.R")
source("ComputeCondDur.R")
source("ComputeC.R")
source("FitFACD.R")
# source("FitWACD.R")
source("FitWACD2.R")
source("FitEACD.R")
source("ComputeOmega.R")
source("ComputeOmega2.R")
source("ComputeOmega3.R")
source("handledata.R")
source("ComputeIS_dual.R")
source("ComputeC_dual.R")
source("ComputeLoglik_dual.R")
source("FitACD_2-stage_correct.R")
# source("FitFACD_fix.R")
source("FitFACD_fix2.R")
setwd("C:/Users/yaoz/Documents/FACDapp/blocktrade/20131202data")

init.wbparam <- c(1, 0.1, 0.2, 0.6)
id.str <- "wb_new"
wbfit <- FitWACD(dur.adj, portmanteau = TRUE, id.str = id.str, init.param = init.wbparam) 

# Output plots
xdata <- seq(from=0, to=7, by=0.01)
wbpar.str <- paste(round(wbfit$param[1],digits=3),round(wbfit$param[2],digits=3), round(wbfit$param[3],digits=3), round(wbfit$param[4],digits=3), sep=", ")

res.den2 <- density(wbfit$res, adj=1)
r <- wbfit$param[1]
theo.den2 <- dweibull(xdata, shape = r, scale = 1 / gamma(1 + 1 / r))
emp.q2 <- quantile(wbfit$res, probs = seq(0.01, 0.99, 0.01))
theo.q2 <- qweibull(p=seq(0.01, 0.99, 0.01), shape = r, scale = 1 / gamma(1 + 1 / r), lower.tail = TRUE)

# pdf(file=paste(id.str, '_plot.pdf', sep=""), width = 16, height = 8)
# par(mfrow=c(2,4), mar=c(5,5,5,5))
plot(theo.den2~xdata, type="l", col="blue", ylim=c(0, 3.5), lty="dashed", main = paste("WACD(1,1):", wbpar.str))
lines(res.den2)
plot(theo.den2~xdata, type="l", col="blue", xlim=c(3, 7), ylim=c(0, 0.1), lty="dashed", main = paste("mean residual = ", round(mean(wbfit$res), digits=3)))
lines(res.den2)
plot(theo.q2, emp.q2, ylim=c(0,12), xlim=c(0,9))
lines(0:20, 0:20)
acf(wbfit$res, ylim=c(-0.03,0.03))
# dev.off()

wbfit1202 <- wbfit
save(wbfit1202, file="wbfit1202.RData")
